export const typeStyles = {
    normal: { backgroundImage: 'url(./images/cards/normal-card.jpg)', backgroundColor: '#A8A77A' },
    fire: { backgroundImage: 'url(./images/cards/fire-card.jpg)', backgroundColor: '#EE8130' },
    water: { backgroundImage: 'url(./images/cards/water-card.jpg)', backgroundColor: '#6390F0' },
    electric: { backgroundImage: 'url(./images/cards/electric-card.jpg)', backgroundColor: '#F7D02C' },
    grass: { backgroundImage: 'url(./images/cards/grass-card.jpg)', backgroundColor: '#7AC74C' },
    ice: { backgroundImage: 'url(./images/cards/ice-card.jpg)', backgroundColor: '#96D9D6' },
    fighting: { backgroundImage: 'url(./images/cards/fighting-card.jpg)', backgroundColor: '#C22E28' },
    poison: { backgroundImage: 'url(./images/cards/poison-card.jpg)', backgroundColor: '#A33EA1' },
    ground: { backgroundImage: 'url(./images/cards/ground-card.jpg)', backgroundColor: '#E2BF65' },
    flying: { backgroundImage: 'url(./images/cards/flying-card.jpg)', backgroundColor: '#A98FF3' },
    psychic: { backgroundImage: 'url(./images/cards/psychic-card.jpg)', backgroundColor: '#F95587' },
    bug: { backgroundImage: 'url(./images/cards/bug-card.jpg)', backgroundColor: '#A6B91A' },
    rock: { backgroundImage: 'url(./images/cards/rock-card.jpg)', backgroundColor: '#B6A136' },
    ghost: { backgroundImage: 'url(./images/cards/ghost-card.jpg)', backgroundColor: '#735797' },
    dragon: { backgroundImage: 'url(./images/cards/dragon-card.jpg)', backgroundColor: '#6F35FC' },
    dark: { backgroundImage: 'url(./images/cards/dark-card.jpg)', backgroundColor: '#705746' },
    steel: { backgroundImage: 'url(./images/cards/steel-card.jpg)', backgroundColor: '#B7B7CE' },
    fairy: { backgroundImage: 'url(./images/cards/fairy-card.jpg)', backgroundColor: '#D685AD' },
};
